name: Lily
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32692
title: Lily the Comic Strip
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#75ff98'
    - '#ffffff'
    - '#b78252'
    - '#2d3429'
    - '#56a867'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
