name: Lily
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: Lily the Comic Strip
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f6ce1e'
    - '#96a673'
    - '#5b4490'
    - '#bf007e'
  brandStrength: 1
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
