name: Lily
favicon: null
layout_spectrum: 0.9731447482481599
typography_spectrum: 0.47981045860797167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6085566806141287
  lightness: 0.1866754423826933
  saturation: 0.021876483457162976
  rhythmicContrast: 0.6066293811891228
purpose: []
