name: Lily
favicon: null
layout_spectrum: 0.25
typography_spectrum: 0
title: Lily the Comic Strip
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#75ff98'
    - '#ffffff'
    - '#b78252'
    - '#2d3429'
    - '#56a867'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
